
public class Project012 {

	/**
	 * The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
	 */
	public static void main(String[] args) {
		// TODO Auto-generated method stub
		int count = 1;
		while(true) {
			int sum = 0;
			for(int i = 1; i <= count; i++) {
				sum = sum + i;
			}
			
			if(divCount(sum) > 500) {
				System.out.println("ans: "+ sum );
				break;
			}
			else {
				count++;
			}
		}
		//ans: 76576500 is correct but took 12 minutes
		//effectively the brute force strat
		//


	}
	
	public static int divCount(int a) {
		//returns the number of divisors
		int count = 0;
		for(int i = 1; i <= a; i++) {
			if(a%i == 0) {
				count++;
			}
			float per = i * 1f / a;
			if( per > 0.55) {
				//speed things up a bit
				count++;
				return count;
			}
				
		}
		return count;
	}

}
